#pragma once
#define AMELTECH_BOT_VERSION "1.0.0"
#define AMELTECH_MAX_KNOWLEDGE_ENTRIES 48
#define AMELTECH_MAX_CONTEXT 8
#define AMELTECH_DEFAULT_CONFIDENCE_STRONG 0.90f
#define AMELTECH_DEFAULT_CONFIDENCE_MODERATE 0.75f
#define AMELTECH_DEFAULT_CONFIDENCE_CLARIFY 0.50f
