// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by tools/generate_knowledge.py from data/knowledge.json
//
// Declarations only. The table itself is defined exactly once, in
// knowledge_generated.cpp, so it occupies one block of flash no matter how
// many translation units include this header.

#ifndef AMELTECH_KNOWLEDGE_GENERATED_H
#define AMELTECH_KNOWLEDGE_GENERATED_H

#include <Arduino.h>

#define AMELTECH_BUILTIN_KNOWLEDGE_COUNT 2037
#define AMELTECH_KNOWLEDGE_REVISION "2.0.0"

struct AmelTechBuiltinEntry {
    const char* question;    // original phrasing, shown to the user
    const char* answer;      // response text
    const char* category;    // topic label
    const char* normalized;  // AmelTechText::normalize(question)
    uint32_t signature;      // AmelTechText::tokenSignature(normalized)
    uint64_t bloom;          // AmelTechText::trigramBloom(normalized)
    uint8_t tokenCount;      // words in normalized
};

// On ESP32 .rodata is mapped into flash (DROM), so plain `const` already keeps
// this out of DRAM and the pointers can be dereferenced directly.
extern const AmelTechBuiltinEntry AMELTECH_BUILTIN_KNOWLEDGE[AMELTECH_BUILTIN_KNOWLEDGE_COUNT];

#endif // AMELTECH_KNOWLEDGE_GENERATED_H
