// =============================================================
// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
//
// Generated by tools/generate_knowledge.py from data/knowledge.json
// Generated at: 2026-08-22T04:16:38Z
// Entry count:  30
//
// To modify the built-in knowledge base, edit data/knowledge.json
// and re-run:
//   python3 tools/generate_knowledge.py
// =============================================================
#ifndef AMELTECH_KNOWLEDGE_GENERATED_H
#define AMELTECH_KNOWLEDGE_GENERATED_H

#include <Arduino.h>

// Stored in flash (PROGMEM) on AVR-style targets; on ESP32, string
// literals in flash-qualified sections are placed in flash/rodata
// automatically by the toolchain, so PROGMEM macros are used for
// portability but are effectively no-ops on ESP32.

struct AmelTechKnowledgeEntryPROGMEM {
    const char* question;
    const char* answer;
    const char* category;
};

#define AMELTECH_GENERATED_KNOWLEDGE_COUNT 30

static const char AMELTECH_KQ_0[] PROGMEM = "what is water";
static const char AMELTECH_KA_0[] PROGMEM = "Water is a chemical compound made of hydrogen and oxygen, H2O.";
static const char AMELTECH_KC_0[] PROGMEM = "science";
static const char AMELTECH_KQ_1[] PROGMEM = "what is gravity";
static const char AMELTECH_KA_1[] PROGMEM = "Gravity is a force of attraction between objects that have mass.";
static const char AMELTECH_KC_1[] PROGMEM = "science";
static const char AMELTECH_KQ_2[] PROGMEM = "what is esp32";
static const char AMELTECH_KA_2[] PROGMEM = "ESP32 is a family of low-cost microcontrollers with integrated Wi-Fi and Bluetooth.";
static const char AMELTECH_KC_2[] PROGMEM = "esp32";
static const char AMELTECH_KQ_3[] PROGMEM = "what is arduino";
static const char AMELTECH_KA_3[] PROGMEM = "Arduino is an open-source platform of hardware and software for building electronics projects.";
static const char AMELTECH_KC_3[] PROGMEM = "esp32";
static const char AMELTECH_KQ_4[] PROGMEM = "how many seconds are there in one minute";
static const char AMELTECH_KA_4[] PROGMEM = "There are 60 seconds in one minute.";
static const char AMELTECH_KC_4[] PROGMEM = "math";
static const char AMELTECH_KQ_5[] PROGMEM = "how many minutes are there in one hour";
static const char AMELTECH_KA_5[] PROGMEM = "There are 60 minutes in one hour.";
static const char AMELTECH_KC_5[] PROGMEM = "math";
static const char AMELTECH_KQ_6[] PROGMEM = "how many hours are there in one day";
static const char AMELTECH_KA_6[] PROGMEM = "There are 24 hours in one day.";
static const char AMELTECH_KC_6[] PROGMEM = "math";
static const char AMELTECH_KQ_7[] PROGMEM = "how many days are there in one week";
static const char AMELTECH_KA_7[] PROGMEM = "There are 7 days in one week.";
static const char AMELTECH_KC_7[] PROGMEM = "math";
static const char AMELTECH_KQ_8[] PROGMEM = "what is the boiling point of water";
static const char AMELTECH_KA_8[] PROGMEM = "Water boils at 100 degrees Celsius (212 degrees Fahrenheit) at sea level.";
static const char AMELTECH_KC_8[] PROGMEM = "science";
static const char AMELTECH_KQ_9[] PROGMEM = "what is the freezing point of water";
static const char AMELTECH_KA_9[] PROGMEM = "Water freezes at 0 degrees Celsius (32 degrees Fahrenheit) at sea level.";
static const char AMELTECH_KC_9[] PROGMEM = "science";
static const char AMELTECH_KQ_10[] PROGMEM = "what is wifi";
static const char AMELTECH_KA_10[] PROGMEM = "Wi-Fi is a wireless networking technology that allows devices to communicate over radio waves.";
static const char AMELTECH_KC_10[] PROGMEM = "esp32";
static const char AMELTECH_KQ_11[] PROGMEM = "what is bluetooth";
static const char AMELTECH_KA_11[] PROGMEM = "Bluetooth is a short-range wireless technology for exchanging data between devices.";
static const char AMELTECH_KC_11[] PROGMEM = "esp32";
static const char AMELTECH_KQ_12[] PROGMEM = "what is i2c";
static const char AMELTECH_KA_12[] PROGMEM = "I2C is a two-wire serial communication protocol used to connect microcontrollers with peripherals.";
static const char AMELTECH_KC_12[] PROGMEM = "esp32";
static const char AMELTECH_KQ_13[] PROGMEM = "what is spi";
static const char AMELTECH_KA_13[] PROGMEM = "SPI is a synchronous serial communication protocol commonly used for fast data transfer between devices.";
static const char AMELTECH_KC_13[] PROGMEM = "esp32";
static const char AMELTECH_KQ_14[] PROGMEM = "what is uart";
static const char AMELTECH_KA_14[] PROGMEM = "UART is a hardware communication protocol used for asynchronous serial data transfer.";
static const char AMELTECH_KC_14[] PROGMEM = "esp32";
static const char AMELTECH_KQ_15[] PROGMEM = "what is gpio";
static const char AMELTECH_KA_15[] PROGMEM = "GPIO stands for General Purpose Input Output, pins that can be configured as digital input or output.";
static const char AMELTECH_KC_15[] PROGMEM = "esp32";
static const char AMELTECH_KQ_16[] PROGMEM = "what is adc";
static const char AMELTECH_KA_16[] PROGMEM = "ADC stands for Analog to Digital Converter, used to read analog voltages as digital values.";
static const char AMELTECH_KC_16[] PROGMEM = "esp32";
static const char AMELTECH_KQ_17[] PROGMEM = "what is dac";
static const char AMELTECH_KA_17[] PROGMEM = "DAC stands for Digital to Analog Converter, used to output an analog voltage from a digital value.";
static const char AMELTECH_KC_17[] PROGMEM = "esp32";
static const char AMELTECH_KQ_18[] PROGMEM = "what is pwm";
static const char AMELTECH_KA_18[] PROGMEM = "PWM stands for Pulse Width Modulation, a technique used to simulate analog output using digital pulses.";
static const char AMELTECH_KC_18[] PROGMEM = "esp32";
static const char AMELTECH_KQ_19[] PROGMEM = "what is rssi";
static const char AMELTECH_KA_19[] PROGMEM = "RSSI stands for Received Signal Strength Indicator, a measurement of Wi-Fi or Bluetooth signal strength.";
static const char AMELTECH_KC_19[] PROGMEM = "esp32";
static const char AMELTECH_KQ_20[] PROGMEM = "what is the speed of light";
static const char AMELTECH_KA_20[] PROGMEM = "The speed of light in a vacuum is approximately 299,792 kilometers per second.";
static const char AMELTECH_KC_20[] PROGMEM = "science";
static const char AMELTECH_KQ_21[] PROGMEM = "what is the capital of france";
static const char AMELTECH_KA_21[] PROGMEM = "The capital of France is Paris.";
static const char AMELTECH_KC_21[] PROGMEM = "general";
static const char AMELTECH_KQ_22[] PROGMEM = "what is photosynthesis";
static const char AMELTECH_KA_22[] PROGMEM = "Photosynthesis is the process by which plants convert light energy into chemical energy.";
static const char AMELTECH_KC_22[] PROGMEM = "science";
static const char AMELTECH_KQ_23[] PROGMEM = "what is a microcontroller";
static const char AMELTECH_KA_23[] PROGMEM = "A microcontroller is a compact integrated circuit designed to govern a specific operation in an embedded system.";
static const char AMELTECH_KC_23[] PROGMEM = "esp32";
static const char AMELTECH_KQ_24[] PROGMEM = "what is flash memory";
static const char AMELTECH_KA_24[] PROGMEM = "Flash memory is a type of non-volatile storage that retains data even when power is removed.";
static const char AMELTECH_KC_24[] PROGMEM = "esp32";
static const char AMELTECH_KQ_25[] PROGMEM = "what is psram";
static const char AMELTECH_KA_25[] PROGMEM = "PSRAM is Pseudo-Static RAM, additional external memory some ESP32 variants use to extend available RAM.";
static const char AMELTECH_KC_25[] PROGMEM = "esp32";
static const char AMELTECH_KQ_26[] PROGMEM = "what is a watchdog timer";
static const char AMELTECH_KA_26[] PROGMEM = "A watchdog timer resets a system if software becomes unresponsive, helping recover from crashes or hangs.";
static const char AMELTECH_KC_26[] PROGMEM = "esp32";
static const char AMELTECH_KQ_27[] PROGMEM = "what is nvs";
static const char AMELTECH_KA_27[] PROGMEM = "NVS stands for Non-Volatile Storage, a key-value storage system used on ESP32 to persist data in flash.";
static const char AMELTECH_KC_27[] PROGMEM = "esp32";
static const char AMELTECH_KQ_28[] PROGMEM = "who created arduino";
static const char AMELTECH_KA_28[] PROGMEM = "Arduino was created in 2005 by a team including Massimo Banzi at the Interaction Design Institute Ivrea.";
static const char AMELTECH_KC_28[] PROGMEM = "general";
static const char AMELTECH_KQ_29[] PROGMEM = "what is ohms law";
static const char AMELTECH_KA_29[] PROGMEM = "Ohm's Law states that voltage equals current multiplied by resistance, V = I x R.";
static const char AMELTECH_KC_29[] PROGMEM = "science";

static const AmelTechKnowledgeEntryPROGMEM AMELTECH_GENERATED_KNOWLEDGE[AMELTECH_GENERATED_KNOWLEDGE_COUNT] PROGMEM = {
    { AMELTECH_KQ_0, AMELTECH_KA_0, AMELTECH_KC_0 },
    { AMELTECH_KQ_1, AMELTECH_KA_1, AMELTECH_KC_1 },
    { AMELTECH_KQ_2, AMELTECH_KA_2, AMELTECH_KC_2 },
    { AMELTECH_KQ_3, AMELTECH_KA_3, AMELTECH_KC_3 },
    { AMELTECH_KQ_4, AMELTECH_KA_4, AMELTECH_KC_4 },
    { AMELTECH_KQ_5, AMELTECH_KA_5, AMELTECH_KC_5 },
    { AMELTECH_KQ_6, AMELTECH_KA_6, AMELTECH_KC_6 },
    { AMELTECH_KQ_7, AMELTECH_KA_7, AMELTECH_KC_7 },
    { AMELTECH_KQ_8, AMELTECH_KA_8, AMELTECH_KC_8 },
    { AMELTECH_KQ_9, AMELTECH_KA_9, AMELTECH_KC_9 },
    { AMELTECH_KQ_10, AMELTECH_KA_10, AMELTECH_KC_10 },
    { AMELTECH_KQ_11, AMELTECH_KA_11, AMELTECH_KC_11 },
    { AMELTECH_KQ_12, AMELTECH_KA_12, AMELTECH_KC_12 },
    { AMELTECH_KQ_13, AMELTECH_KA_13, AMELTECH_KC_13 },
    { AMELTECH_KQ_14, AMELTECH_KA_14, AMELTECH_KC_14 },
    { AMELTECH_KQ_15, AMELTECH_KA_15, AMELTECH_KC_15 },
    { AMELTECH_KQ_16, AMELTECH_KA_16, AMELTECH_KC_16 },
    { AMELTECH_KQ_17, AMELTECH_KA_17, AMELTECH_KC_17 },
    { AMELTECH_KQ_18, AMELTECH_KA_18, AMELTECH_KC_18 },
    { AMELTECH_KQ_19, AMELTECH_KA_19, AMELTECH_KC_19 },
    { AMELTECH_KQ_20, AMELTECH_KA_20, AMELTECH_KC_20 },
    { AMELTECH_KQ_21, AMELTECH_KA_21, AMELTECH_KC_21 },
    { AMELTECH_KQ_22, AMELTECH_KA_22, AMELTECH_KC_22 },
    { AMELTECH_KQ_23, AMELTECH_KA_23, AMELTECH_KC_23 },
    { AMELTECH_KQ_24, AMELTECH_KA_24, AMELTECH_KC_24 },
    { AMELTECH_KQ_25, AMELTECH_KA_25, AMELTECH_KC_25 },
    { AMELTECH_KQ_26, AMELTECH_KA_26, AMELTECH_KC_26 },
    { AMELTECH_KQ_27, AMELTECH_KA_27, AMELTECH_KC_27 },
    { AMELTECH_KQ_28, AMELTECH_KA_28, AMELTECH_KC_28 },
    { AMELTECH_KQ_29, AMELTECH_KA_29, AMELTECH_KC_29 },
};

#endif // AMELTECH_KNOWLEDGE_GENERATED_H
